name: CI Workflow

on:
  pull_request:
    branches:
      - '**'  # Run lint on all pull requests

  push:
    branches:
      - main  # Deploy only on pushes to the main branch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn install
      - name: Run Lint
        run: yarn lint

  build-and-deploy:
    if: github.ref == 'refs/heads/main'  # Deploy only from the main branch
    runs-on: ubuntu-latest
    needs: lint  # Ensure lint passes in the PR before merging to main
    steps:
      - uses: actions/checkout@v2
      - name: Download Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "herenow"
          heroku_email: "ira@leyconnect.com"
